### ISSUE TITLE
Missing 'filter_waymo.txt' and  'waymo_calibs.pkl'

### ISSUE THREAD

**Issue by synsin0** [OpenDriveLab/Birds-eye-view-Perception#11]
Thanks for your waymo support of bevformer! I am missing some files. They are 'filter_waymo.txt' and  'waymo_calibs.pkl', Are they included in waymo_mini google drive or we need to generate by ourselves?

**Comment by cyberknight42** [comment]
Yes, they are in the waymo_mini on the google drive

**Comment by YongtaoGe** [comment]
@cyberknight42 hi, thanks for your work. I down the tar.gz files from google drive. After extracting the files, I only got the training folder with image_0, image_2, image_3, and filter_waymo.txt, but pkl files and gt bin files are missing.
