### ISSUE TITLE
How to unzip the waymo_mini dataset in Google drive?

### ISSUE THREAD

**Issue by exiawsh** [OpenDriveLab/Birds-eye-view-Perception#15]
Hi, 
thanks for the great work!
It seems that there is something wrong with the waymo_mini dataset in Google drive.
When I download the data and using tar -zxvf ./waymo_mini.tar-015.gz00 to extract the data, an error occurred:

gzip: stdin: unexpected end of file          
tar: Unexpected EOF in archive               
tar: Unexpected EOF in archive               
tar: Error is not recoverable: exiting now   
How to solve that?
The size of the data seems right.

**Comment by ChonghaoSima** [comment]
Hi, as the waymo mini dataset is still too large, we split it into several files. Have you download all the files and tar the first file?

**Comment by exiawsh** [comment]
Hi, I download 39 files in total, is that right? And could I have your wechat?

**Comment by cyberknight42** [comment]
Did you use the following commands to extract these files? 
```
cat waymo_mini*>waymo_mini.tar.gz
tar xzvf waymo_mini.tar.gz 
```

**Comment by exiawsh** [comment]
> 

I will try this, thank you! 
I used tar -zxvf ./waymo_mini.tar.gz00 before.

**Comment by exiawsh** [comment]
> Did you use the following commands to extract these files?
> 
> ```
> cat waymo_mini*>waymo_mini.tar.gz
> tar xzvf waymo_mini.tar.gz 
> ```

It works. Thank you!

**Comment by exiawsh** [comment]
> Did you use the following commands to extract these files?
> 
> ```
> cat waymo_mini*>waymo_mini.tar.gz
> tar xzvf waymo_mini.tar.gz 
> ```

Sorry to bother you again. I successfully merge all the tar.gz files. I finally got waymo_mini.tar.gz with size of 206.8GB.
But it still has some problem.
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by exiawsh** [comment]
> > Did you use the following commands to extract these files?
> > ```
> > cat waymo_mini*>waymo_mini.tar.gz
> > tar xzvf waymo_mini.tar.gz 
> > ```
> 
> Sorry to bother you again. I successfully merge all the tar.gz files. I finally got waymo_mini.tar.gz with size of 206.8GB. But it still has some problem. gzip: stdin: unexpected end of file tar: Child returned status 1 tar: Error is not recoverable: exiting now

I will re-download the all the files. If there are still some problems. I will contact you.

**Comment by exiawsh** [comment]
> Did you use the following commands to extract these files?
> 
> ```
> cat waymo_mini*>waymo_mini.tar.gz
> tar xzvf waymo_mini.tar.gz 
> ```

And would you please share the pkl file separately?

**Comment by exiawsh** [comment]
> Did you use the following commands to extract these files?
> 
> ```
> cat waymo_mini*>waymo_mini.tar.gz
> tar xzvf waymo_mini.tar.gz 
> ```
Hello, I re-download all the files. 
And I used to extract the waymo_mini.
cat waymo_mini*>waymo_mini.tar.gz
tar xzvf waymo_mini.tar.gz 
I still got the following error. I think you may update the google cloud.
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by exiawsh** [comment]
I found the problem. I **packed** and downloaded all the files from Google Cloud.  I don't know whether the problem is in the downloader or Google Cloud. When **packaging** and downloading, a number suffix will be added after the file name tar. The number suffix can be downloaded normally after being deleted.
For example the file name will change when packing:
waymo_mini.tar.gz22 -> waymo_mini.tar**03**.gz22
deleting the "03", the problem can be solved.
Thank you!
