### ISSUE TITLE
 missing  'filter_waymo.txt' and 'waymo_calibs.pkl'

### ISSUE THREAD

**Issue by Orange-rightperson** [OpenDriveLab/Birds-eye-view-Perception#17]
Hello, I want to run this program on full waymo dataset but I am missing  'filter_waymo.txt' and 'waymo_calibs.pkl'. Could you please telll me how can I generate them?

**Comment by ChonghaoSima** [comment]
Please refer to #11 . And we have updated the unzip command of the downloaded files for your convenience.
