### ISSUE TITLE
the waymo_mini dataset in Google drive is no longer valid

### ISSUE THREAD

**Issue by linqx7** [OpenDriveLab/Birds-eye-view-Perception#19]
Can you upload the dataset again?

**Comment by faikit** [comment]
solved in commit [c6be99409ecc84d50825a614cc844a7ede7440e1](https://github.com/OpenDriveLab/Birds-eye-view-Perception/commit/c6be99409ecc84d50825a614cc844a7ede7440e1)

**Comment by linqx7** [comment]
您好，您的邮件我已收到，我会尽快阅读。
