### ISSUE TITLE
'waymo_setup.md' is 404 - page not found

### ISSUE THREAD

**Issue by flyzenr** [OpenDriveLab/Birds-eye-view-Perception#20]
Hello, I want to run experiments on Waymo by refering to [waymo_setup.md](https://github.com/OpenDriveLab/Birds-eye-view-Perception/blob/master/bev_toolbox/docs/waymo_setup.md), however, the page is not found.

**Comment by EthanJi29** [comment]
It's now in https://github.com/OpenDriveLab/Birds-eye-view-Perception/blob/master/docs/waymo_setup.md

**Comment by ChonghaoSima** [comment]
Thanks for answering!
