### ISSUE TITLE
git clone https://gitee.com/lizhiqi-gitee/bevformer.git access denied

### ISSUE THREAD

**Issue by 1146065545** [OpenDriveLab/Birds-eye-view-Perception#21]
git clone https://gitee.com/lizhiqi-gitee/bevformer.git
The requested URL returned error: 403

**Comment by EthanJi29** [comment]
This repository seems to be deprecated. Try: 
git clone https://github.com/fundamentalvision/BEVFormer.git

**Comment by ChonghaoSima** [comment]
Thanks for answering!
