### ISSUE TITLE
pretrained model on waymo

### ISSUE THREAD

**Issue by ZJLi2013** [OpenDriveLab/Birds-eye-view-Perception#23]
hi, dear author,  has the repo provided waymo(or waymo mini) pertained models?   looks the pretrained models  in [data prepartion](https://github.com/OpenDriveLab/Birds-eye-view-Perception/blob/master/docs/data_preparation.md) is nu-scenes based, would like to do some validation on waymo, thanks a lot

**Comment by Zeng-Jia** [comment]
The pretrained weights on Waymo dataset could not be distributed due to [Waymo Dataset License Agreement](https://waymo.com/open/terms/).
