### ISSUE TITLE
Code of FocalDistiller

### ISSUE THREAD

**Issue by Debrove** [OpenDriveLab/Birds-eye-view-Perception#24]
Hi! I am very interested in the FocalDistiller!

Could you have a plan to open-source the core code of the FocalDistiller? Just the loss code is also OK!

Looking forward to your reply. Thank you!

**Comment by Zeng-Jia** [comment]
FocalDistiller is scheduled for expanding into journal paper. Currently, the implementation of FocalDistiller is not accessible, but we have made its codebase available (see https://github.com/OpenDriveLab/Birds-eye-view-Perception/tree/master/nuScenes_playground/FocalDistiller), which includes an effective baseline distillation method.
