### ISSUE TITLE
你好，请问focaldistill的权重如何获得？谷歌网盘需要权限。

### ISSUE THREAD

**Issue by linqx7** [OpenDriveLab/Birds-eye-view-Perception#28]

**Comment by Zeng-Jia** [comment]
Sorry, the access permission of model weight has been corrected.

**Comment by linqx7** [comment]
您好，您的邮件我已收到，我会尽快阅读。

**Comment by Zeng-Jia** [comment]
We add the download link from Baidu Disk. address: https://pan.baidu.com/s/1_AD4Q1pCB2feB9hN1a6wsA?pwd=8888 code:8888
